gitlab-runner:
  image:
    registry: registry.gitlab.com
    image: gitlab-org/gitlab-runner
  imagePullPolicy: IfNotPresent
  replicas: 5
  gitlabUrl: https://gitlab.savis.vn/
  runnerRegistrationToken: "GR1348941ETBsSFyxCNLhuGstw2iF"


  terminationGracePeriodSeconds: 3600


  concurrent: 10


  checkInterval: 30

 
  sessionServer:
    enabled: false

  rbac:
    create: true
    rules:
      - apiGroups: [""]
        resources: ["pods", "secrets", "configmaps"]
        verbs: ["get", "list", "watch", "create", "patch", "delete", "update"]
      - apiGroups: [""]
        resources: ["pods/exec", "pods/attach"]
        verbs: ["create", "patch", "delete"]
      - apiGroups: [""]
        resources: ["pods/log"]
        verbs: ["get"]

    clusterWideAccess: false

    podSecurityPolicy:
      enabled: false
      resourceNames:
      - gitlab-runner


  metrics:
    enabled: false


    portName: metrics


    port: 9252


    serviceMonitor:
      enabled: false


  service:
    enabled: false

    type: ClusterIP

  runners:

    config: |
      [[runners]]
        [runners.kubernetes]
          namespace = "{{.Release.Namespace}}"
          image = "ubuntu:16.04"
          [[runners.kubernetes.host_aliases]]
            ip = "192.168.10.5"
            hostnames = ["gitlab.savis.vn"]


    tags: "dev2"


    cache: {}

    builds: {}

    services: {}

    helpers: {}



  securityContext:
    allowPrivilegeEscalation: false
    readOnlyRootFilesystem: false
    runAsNonRoot: true
    privileged: false
    capabilities:
      drop: ["ALL"]


  podSecurityContext:
    runAsUser: 100
    # runAsGroup: 65533
    fsGroup: 65533
    # supplementalGroups: [65533]


  resources: {}

  affinity: {}

  nodeSelector: {}

  tolerations: []

  hostAliases:
    - ip: "10.0.20.6"
      hostnames:
      - "dev-servlet-https-test.savis.vn"
    - ip: "192.168.10.5"
      hostnames:
      - "gitlab.savis.vn"
      
  podAnnotations: {}

  podLabels: {}

  priorityClassName: ""


  secrets: []


  configMaps: {}

  volumeMounts: []

  volumes: []



